### ISSUE TITLE
non integer value for char field in project_invoice

### ISSUE THREAD

**Issue by RaffaeleT** [OpusVL/odoo-project-management#10]
in project_invoice/project.py, in field definition:
instead of type="char", size="512", 
should be type="char", size=512,

**Comment by Nick-OpusVL** [comment]
Hi @RaffaeleT I've put your fix in directly.  Can you please check that patch is what you'd expect and test the code from the master branch?

**Comment by Nick-OpusVL** [comment]
@RaffealeT

Note I've now set the default branch on github to be 8.0, where I've moved the unported modules including project_invoice into an `__unported__` directory, to follow the usual convention used by OCA.
I've left the 'master' branch as it is, but it won't get further updates.  If the project_invoice actually does what it's supposed to now I've changed that size= issue, could you please let me know and I'll look at moving it out of `__unported__`.

**Comment by RaffaeleT** [comment]
@Nick-OpusVL thank you, I confirm the issue is resolved and yes, the module does what it's supposed to do.
